AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AYD document processing infra

Parameters:
  Environment:
    Type: String
    Default: dev

  DocumentBucketName:
    Type: String
    Default: ayd-workspace-jay-docs

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  IngestionDlq:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "ayd-ingestion-dlq-${Environment}"

  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "ayd-ingestion-queue-${Environment}"
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IngestionDlq.Arn
        maxReceiveCount: 2

  IngestionQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IngestionQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3SendMessage
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt IngestionQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:s3:::${DocumentBucketName}"

  DocumentsBucket:
    Type: AWS::S3::Bucket
    DependsOn: IngestionQueuePolicy
    Properties:
      BucketName: !Ref DocumentBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - http://localhost:3000
            AllowedMethods:
              - PUT
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt IngestionQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .pdf

  IngestionWorkerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../../workers/ingestion-worker
      DockerTag: python312-v1
    Properties:
      PackageType: Image
      FunctionName: !Sub "ayd-ingestion-worker-${Environment}"
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaSQSQueueExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Sid: AllowReadDocumentsBucket
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${DocumentBucketName}/*"

            - Sid: AllowListDocumentsBucket
              Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub "arn:aws:s3:::${DocumentBucketName}"

            - Sid: AllowBedrockEmbedding
              Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: arn:aws:bedrock:ap-south-1::foundation-model/amazon.titan-embed-text-v2:0

      Environment:
        Variables:
          APP_ENV: !Ref Environment
          LOG_LEVEL: INFO
          DOCUMENTS_BUCKET_NAME: !Ref DocumentBucketName
          BEDROCK_REGION: ap-south-1
          EMBEDDING_MODEL_ID: amazon.titan-embed-text-v2:0
          DATABASE_URL: "postgresql://postgres:Jay_post26@ayd-postgres.czgweeg08232.ap-south-1.rds.amazonaws.com:5432/ayd_db"

      Events:
        IngestionQueueTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt IngestionQueue.Arn
            BatchSize: 1

  OcrResultsWorkerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ../../workers/ocr-results-worker
      DockerTag: python312-v1
    Properties:
      PackageType: Image
      FunctionName: !Sub "ayd-ocr-results-worker-${Environment}"
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_ENV: !Ref Environment
          LOG_LEVEL: INFO
          DOCUMENTS_BUCKET_NAME: !Ref DocumentBucketName

Outputs:
  DocumentBucketName:
    Value: !Ref DocumentsBucket

  IngestionQueueArn:
    Value: !GetAtt IngestionQueue.Arn

  IngestionDlqArn:
    Value: !GetAtt IngestionDlq.Arn

  IngestionWorkerFunctionName:
    Value: !Ref IngestionWorkerFunction

  OcrResultsWorkerFunctionName:
    Value: !Ref OcrResultsWorkerFunction